const nftData = [
    {
        nftImageUrl: "https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/Nft3.3b3e6a4b3ada7618de6c.png",
        profileImageUrl: "https://uniwave-main.s3.eu-central-1.amazonaws.com/gg.JPG",
        name: "Wood Workshop Certificate",
        creationDate: "21.08.2023",
        certificationType: "Craftsmanship Certification",
        onProfileClick: () => console.log("Profile clicked"),
        onViewClick: () => console.log("View clicked"),
    },
    {
        nftImageUrl: "https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/Nft3.3b3e6a4b3ada7618de6c.png",
        profileImageUrl: "https://uniwave-main.s3.eu-central-1.amazonaws.com/gg.JPG",
        name: "Wood Workshop Certificate",
        creationDate: "21.08.2023",
        certificationType: "Craftsmanship Certification",
        onProfileClick: () => console.log("Profile clicked"),
        onViewClick: () => console.log("View clicked"),
    },
    {
        nftImageUrl: "https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/Nft3.3b3e6a4b3ada7618de6c.png",
        profileImageUrl: "https://uniwave-main.s3.eu-central-1.amazonaws.com/gg.JPG",
        name: "Wood Workshop Certificate",
        creationDate: "21.08.2023",
        certificationType: "Craftsmanship Certification",
        onProfileClick: () => console.log("Profile clicked"),
        onViewClick: () => console.log("View clicked"),
    },
    {
        nftImageUrl: "https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/Nft3.3b3e6a4b3ada7618de6c.png",
        profileImageUrl: "https://uniwave-main.s3.eu-central-1.amazonaws.com/gg.JPG",
        name: "Wood Workshop Certificate",
        creationDate: "21.08.2023",
        certificationType: "Craftsmanship Certification",
        onProfileClick: () => console.log("Profile clicked"),
        onViewClick: () => console.log("View clicked"),
    },
    {
        nftImageUrl: "https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/Nft3.3b3e6a4b3ada7618de6c.png",
        profileImageUrl: "https://uniwave-main.s3.eu-central-1.amazonaws.com/gg.JPG",
        name: "Wood Workshop Certificate",
        creationDate: "21.08.2023",
        certificationType: "Craftsmanship Certification",
        onProfileClick: () => console.log("Profile clicked"),
        onViewClick: () => console.log("View clicked"),
    },
    {
        nftImageUrl: "https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/Nft3.3b3e6a4b3ada7618de6c.png",
        profileImageUrl: "https://uniwave-main.s3.eu-central-1.amazonaws.com/gg.JPG",
        name: "Wood Workshop Certificate",
        creationDate: "21.08.2023",
        certificationType: "Craftsmanship Certification",
        onProfileClick: () => console.log("Profile clicked"),
        onViewClick: () => console.log("View clicked"),
    },
    {
        nftImageUrl: "https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/Nft3.3b3e6a4b3ada7618de6c.png",
        profileImageUrl: "https://uniwave-main.s3.eu-central-1.amazonaws.com/gg.JPG",
        name: "Wood Workshop Certificate",
        creationDate: "21.08.2023",
        certificationType: "Craftsmanship Certification",
        onProfileClick: () => console.log("Profile clicked"),
        onViewClick: () => console.log("View clicked"),
    },
    {
        nftImageUrl: "https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/media/Nft3.3b3e6a4b3ada7618de6c.png",
        profileImageUrl: "https://uniwave-main.s3.eu-central-1.amazonaws.com/gg.JPG",
        name: "Wood Workshop Certificate",
        creationDate: "21.08.2023",
        certificationType: "Craftsmanship Certification",
        onProfileClick: () => console.log("Profile clicked"),
        onViewClick: () => console.log("View clicked"),
    },

    // Diğer kartlar buraya eklenir...
];

export default nftData;
